// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class ImagesRes {
  ImagesRes._();

  static const String PROJECT_NAME = 'namma_srivi';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String BG_BLUE = 'images/Bg-Blue.png';
  static const String BG_RED = 'images/Bg-Red.png';
  static const String BG_YELLOW = 'images/Bg-Yellow.png';
  static const String ILLUSTRATION_BLUE = 'images/Illustration-Blue.png';
  static const String ILLUSTRATION_RED = 'images/Illustration-Red.png';
  static const String ILLUSTRATION_YELLOW = 'images/Illustration-Yellow.png';
  static const String MOON_CRESCENT = 'images/Moon-Crescent.png';
  static const String NEED_HELP = 'images/Need help.png';
  static const String ORDER_NOW = 'images/Order Now.png';
  static const String PLACES_TEMPLE = 'images/Places Temple.png';
  static const String SLIDER_BLUE = 'images/Slider-Blue.png';
  static const String SLIDER_RED = 'images/Slider-Red.png';
  static const String SLIDER_YELLOW = 'images/Slider-Yellow.png';
  static const String SUN_RED = 'images/Sun-Red.png';
  static const String SUN_YELLOW = 'images/Sun-Yellow.png';
  static const String TEMPLE = 'images/Temple.jpg';
  static const String TEMPLE_NEARBY = 'images/Temple_Nearby.png';
  static const String MILK_PALKOVA = 'images/milk palkova.jpg';
  static const String PALKOVA = 'images/palkova.jpg';
}
